// <auto-generated />
using System;
using IRIS.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IRIS.Core.Migrations
{
    [DbContext(typeof(IRISDbContext))]
    [Migration("20260412160932_AddPendingCommands")]
    partial class AddPendingCommands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IRIS.Core.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlertKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("IsResolved", "CreatedAt");

                    b.HasIndex("PCId", "AlertKey", "IsResolved");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("IRIS.Core.Models.DeploymentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PCId")
                        .HasColumnType("integer");

                    b.Property<string>("PCName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PCId", "Timestamp");

                    b.ToTable("DeploymentLogs");
                });

            modelBuilder.Entity("IRIS.Core.Models.HardwareMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CpuTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("double precision");

                    b.Property<double?>("DiskReadSpeed")
                        .HasColumnType("double precision");

                    b.Property<long?>("DiskTotal")
                        .HasColumnType("bigint");

                    b.Property<double?>("DiskUsage")
                        .HasColumnType("double precision");

                    b.Property<long?>("DiskUsed")
                        .HasColumnType("bigint");

                    b.Property<double?>("DiskWriteSpeed")
                        .HasColumnType("double precision");

                    b.Property<long?>("GpuMemoryTotal")
                        .HasColumnType("bigint");

                    b.Property<long?>("GpuMemoryUsed")
                        .HasColumnType("bigint");

                    b.Property<double?>("GpuTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpuUsage")
                        .HasColumnType("double precision");

                    b.Property<long?>("MemoryTotal")
                        .HasColumnType("bigint");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("double precision");

                    b.Property<long?>("MemoryUsed")
                        .HasColumnType("bigint");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PCId", "Timestamp");

                    b.ToTable("HardwareMetrics");
                });

            modelBuilder.Entity("IRIS.Core.Models.NetworkMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long?>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<double?>("DownloadSpeed")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latency")
                        .HasColumnType("double precision");

                    b.Property<string>("NetworkInterface")
                        .HasColumnType("text");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.Property<double?>("PacketLoss")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("UploadSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PCId", "Timestamp");

                    b.ToTable("NetworkMetrics");
                });

            modelBuilder.Entity("IRIS.Core.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultGateway")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubnetMask")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("PCs");
                });

            modelBuilder.Entity("IRIS.Core.Models.PCHardwareConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GraphicsCard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Motherboard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.Property<string>("Processor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("RamCapacity")
                        .HasColumnType("bigint");

                    b.Property<long?>("StorageCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PCId");

                    b.ToTable("PCHardwareConfigs");
                });

            modelBuilder.Entity("IRIS.Core.Models.PendingCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Payload")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress", "Status");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("PendingCommands");
                });

            modelBuilder.Entity("IRIS.Core.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutoShutdownIdleMinutes")
                        .HasColumnType("integer");

                    b.Property<double>("CpuTemperatureCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuTemperatureWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuUsageCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuUsageWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CriticalSustainSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("DiskUsageCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsageWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("GpuTemperatureCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("GpuTemperatureWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("LatencyCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("LatencyWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("PacketLossCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("PacketLossWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("RamUsageCriticalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("RamUsageWarningThreshold")
                        .HasColumnType("double precision");

                    b.Property<bool>("ResetWallpaperOnStartup")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WallpaperPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("WarningSustainSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Name")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("IRIS.Core.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Architecture Computer Lab 1",
                            IsActive = true,
                            RoomNumber = "Lab 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Architecture Computer Lab 2",
                            IsActive = true,
                            RoomNumber = "Lab 2"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Architecture Computer Lab 3",
                            IsActive = true,
                            RoomNumber = "Lab 3"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Architecture Computer Lab 4",
                            IsActive = true,
                            RoomNumber = "Lab 4"
                        });
                });

            modelBuilder.Entity("IRIS.Core.Models.SoftwareUsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PCId", "StartTime");

                    b.ToTable("SoftwareUsageHistory");
                });

            modelBuilder.Entity("IRIS.Core.Models.SystemSettings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "DataRetention.HardwareMetricDays",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Key = "DataRetention.NetworkMetricDays",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Key = "DataRetention.ResolvedAlertDays",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "90"
                        },
                        new
                        {
                            Key = "DataRetention.CleanupHourUtc",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "2"
                        });
                });

            modelBuilder.Entity("IRIS.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$e6AtSfzSfXfCHsk5yjXWIuzIGGfaXRe/Z1GnuMxYx1nfSXlVepAN.",
                            Role = "SystemAdministrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$1Unk6pMkXdwNQjxP3m96M.DggxMbjbSx57fN9TQ6YWwtObK5SFwwO",
                            Role = "ITPersonnel",
                            Username = "itperson"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$TMXewyIW8gRGGutz2DDDbeVLEMp9mVyhlijNJvMXzbV5tdZwH07Si",
                            Role = "Faculty",
                            Username = "faculty"
                        });
                });

            modelBuilder.Entity("IRIS.Core.Models.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int?>("PCId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PCId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("IRIS.Core.Models.WebsiteUsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PCId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PCId", "Browser", "Domain", "VisitedAt")
                        .IsUnique();

                    b.ToTable("WebsiteUsageHistory");
                });

            modelBuilder.Entity("IRIS.Core.Models.Alert", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("Alerts")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IRIS.Core.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IRIS.Core.Models.DeploymentLog", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany()
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PC");
                });

            modelBuilder.Entity("IRIS.Core.Models.HardwareMetric", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("HardwareMetrics")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("IRIS.Core.Models.NetworkMetric", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("NetworkMetrics")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("IRIS.Core.Models.PC", b =>
                {
                    b.HasOne("IRIS.Core.Models.Room", "Room")
                        .WithMany("PCs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IRIS.Core.Models.PCHardwareConfig", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("HardwareConfigs")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("IRIS.Core.Models.Policy", b =>
                {
                    b.HasOne("IRIS.Core.Models.Room", "Room")
                        .WithMany("Policies")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IRIS.Core.Models.SoftwareUsageHistory", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("SoftwareUsageHistory")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("IRIS.Core.Models.UserLog", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("UserLogs")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IRIS.Core.Models.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IRIS.Core.Models.WebsiteUsageHistory", b =>
                {
                    b.HasOne("IRIS.Core.Models.PC", "PC")
                        .WithMany("WebsiteUsageHistory")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PC");
                });

            modelBuilder.Entity("IRIS.Core.Models.PC", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("HardwareConfigs");

                    b.Navigation("HardwareMetrics");

                    b.Navigation("NetworkMetrics");

                    b.Navigation("SoftwareUsageHistory");

                    b.Navigation("UserLogs");

                    b.Navigation("WebsiteUsageHistory");
                });

            modelBuilder.Entity("IRIS.Core.Models.Room", b =>
                {
                    b.Navigation("PCs");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("IRIS.Core.Models.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
