CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Rooms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomNumber" character varying(50) NOT NULL,
    "Description" character varying(100),
    "Capacity" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
);

CREATE TABLE "Software" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500),
    "Version" character varying(50),
    "DownloadUrl" character varying(500),
    "IsApproved" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Software" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "Role" text NOT NULL,
    "FullName" character varying(100),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "PCs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MacAddress" character varying(50) NOT NULL,
    "IpAddress" character varying(50),
    "SubnetMask" character varying(50),
    "DefaultGateway" character varying(50),
    "RoomId" integer NOT NULL,
    "Hostname" character varying(100),
    "OperatingSystem" character varying(100),
    "Status" text NOT NULL,
    "LastSeen" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PCs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PCs_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Policies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "RoomId" integer NOT NULL,
    "ResetWallpaperOnStartup" boolean NOT NULL,
    "EnableAccessControl" boolean NOT NULL,
    "AutoShutdownEnabled" boolean NOT NULL,
    "AutoShutdownIdleMinutes" integer,
    "ScheduledShutdownTime" interval,
    "BlockUnauthorizedApplications" boolean NOT NULL,
    "MonitorApplicationUsage" boolean NOT NULL,
    "MonitorWebsiteUsage" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Policies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Policies_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SoftwareRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "SoftwareId" integer NOT NULL,
    "Reason" character varying(500),
    "Status" text NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedByUserId" integer,
    CONSTRAINT "PK_SoftwareRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SoftwareRequests_Software_SoftwareId" FOREIGN KEY ("SoftwareId") REFERENCES "Software" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SoftwareRequests_Users_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SoftwareRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Alerts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "Severity" text NOT NULL,
    "Type" text NOT NULL,
    "IsAcknowledged" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AcknowledgedAt" timestamp with time zone,
    CONSTRAINT "PK_Alerts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Alerts_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Alerts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "HardwareMetrics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "CpuUsage" double precision,
    "CpuTemperature" double precision,
    "MemoryUsage" double precision,
    "MemoryUsed" bigint,
    "MemoryTotal" bigint,
    "GpuUsage" double precision,
    "GpuTemperature" double precision,
    "GpuMemoryUsed" bigint,
    "GpuMemoryTotal" bigint,
    "DiskUsage" double precision,
    "DiskUsed" bigint,
    "DiskTotal" bigint,
    "DiskReadSpeed" double precision,
    "DiskWriteSpeed" double precision,
    CONSTRAINT "PK_HardwareMetrics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HardwareMetrics_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "NetworkMetrics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "DownloadSpeed" double precision,
    "UploadSpeed" double precision,
    "BytesReceived" bigint,
    "BytesSent" bigint,
    "Latency" double precision,
    "PacketLoss" double precision,
    "IsConnected" boolean,
    "NetworkInterface" text,
    CONSTRAINT "PK_NetworkMetrics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NetworkMetrics_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PCHardwareConfigs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "Processor" character varying(100),
    "GraphicsCard" character varying(100),
    "Motherboard" character varying(100),
    "RamCapacity" bigint,
    "StorageCapacity" bigint,
    "StorageType" character varying(50),
    "AppliedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_PCHardwareConfigs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PCHardwareConfigs_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SoftwareInstalled" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "SoftwareId" integer NOT NULL,
    "InstalledVersion" character varying(50),
    "InstalledAt" timestamp with time zone NOT NULL,
    "UninstalledAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_SoftwareInstalled" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SoftwareInstalled_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SoftwareInstalled_Software_SoftwareId" FOREIGN KEY ("SoftwareId") REFERENCES "Software" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SoftwareUsageHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "ApplicationName" character varying(200) NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "Duration" interval,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SoftwareUsageHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SoftwareUsageHistory_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PCId" integer,
    "Action" character varying(100) NOT NULL,
    "Details" character varying(500),
    "Timestamp" timestamp with time zone NOT NULL,
    "IpAddress" text,
    CONSTRAINT "PK_UserLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserLogs_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UserLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "WebsiteUsageHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "Domain" character varying(200),
    "VisitedAt" timestamp with time zone NOT NULL,
    "VisitCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WebsiteUsageHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WebsiteUsageHistory_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Alerts_PCId" ON "Alerts" ("PCId");

CREATE INDEX "IX_Alerts_UserId" ON "Alerts" ("UserId");

CREATE INDEX "IX_HardwareMetrics_PCId_Timestamp" ON "HardwareMetrics" ("PCId", "Timestamp");

CREATE INDEX "IX_NetworkMetrics_PCId_Timestamp" ON "NetworkMetrics" ("PCId", "Timestamp");

CREATE INDEX "IX_PCHardwareConfigs_PCId" ON "PCHardwareConfigs" ("PCId");

CREATE UNIQUE INDEX "IX_PCs_MacAddress" ON "PCs" ("MacAddress");

CREATE INDEX "IX_PCs_RoomId" ON "PCs" ("RoomId");

CREATE UNIQUE INDEX "IX_Policies_RoomId_Name" ON "Policies" ("RoomId", "Name");

CREATE UNIQUE INDEX "IX_Rooms_RoomNumber" ON "Rooms" ("RoomNumber");

CREATE UNIQUE INDEX "IX_Software_Name" ON "Software" ("Name");

CREATE UNIQUE INDEX "IX_SoftwareInstalled_PCId_SoftwareId" ON "SoftwareInstalled" ("PCId", "SoftwareId");

CREATE INDEX "IX_SoftwareInstalled_SoftwareId" ON "SoftwareInstalled" ("SoftwareId");

CREATE INDEX "IX_SoftwareRequests_ReviewedByUserId" ON "SoftwareRequests" ("ReviewedByUserId");

CREATE INDEX "IX_SoftwareRequests_SoftwareId" ON "SoftwareRequests" ("SoftwareId");

CREATE INDEX "IX_SoftwareRequests_UserId" ON "SoftwareRequests" ("UserId");

CREATE INDEX "IX_SoftwareUsageHistory_PCId_StartTime" ON "SoftwareUsageHistory" ("PCId", "StartTime");

CREATE INDEX "IX_UserLogs_PCId" ON "UserLogs" ("PCId");

CREATE INDEX "IX_UserLogs_UserId_Timestamp" ON "UserLogs" ("UserId", "Timestamp");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

CREATE INDEX "IX_WebsiteUsageHistory_PCId_VisitedAt" ON "WebsiteUsageHistory" ("PCId", "VisitedAt");

INSERT INTO "Rooms" ("Id", "RoomNumber", "Description", "Capacity", "IsActive", "CreatedAt")
VALUES (1, 'DEFAULT', 'Default room for unassigned PCs', 0, TRUE, TIMESTAMPTZ '2025-01-01T00:00:00Z');

INSERT INTO "Users" ("Id", "Username", "PasswordHash", "Role", "FullName", "IsActive", "CreatedAt", "LastLoginAt")
VALUES (1, 'admin', '$2a$11$e6AtSfzSfXfCHsk5yjXWIuzIGGfaXRe/Z1GnuMxYx1nfSXlVepAN.', 'SystemAdministrator', NULL, TRUE, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL);
INSERT INTO "Users" ("Id", "Username", "PasswordHash", "Role", "FullName", "IsActive", "CreatedAt", "LastLoginAt")
VALUES (2, 'itperson', '$2a$11$1Unk6pMkXdwNQjxP3m96M.DggxMbjbSx57fN9TQ6YWwtObK5SFwwO', 'ITPersonnel', NULL, TRUE, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL);
INSERT INTO "Users" ("Id", "Username", "PasswordHash", "Role", "FullName", "IsActive", "CreatedAt", "LastLoginAt")
VALUES (3, 'faculty', '$2a$11$TMXewyIW8gRGGutz2DDDbeVLEMp9mVyhlijNJvMXzbV5tdZwH07Si', 'Faculty', NULL, TRUE, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL);

SELECT setval(
    pg_get_serial_sequence('"Rooms"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Rooms") + 1,
        nextval(pg_get_serial_sequence('"Rooms"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251014161408_InitialCreate', '9.0.9');

ALTER TABLE "Users" ADD "MustChangePassword" boolean NOT NULL DEFAULT FALSE;

UPDATE "Users" SET "MustChangePassword" = FALSE
WHERE "Id" = 1;

UPDATE "Users" SET "MustChangePassword" = FALSE
WHERE "Id" = 2;

UPDATE "Users" SET "MustChangePassword" = FALSE
WHERE "Id" = 3;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260104160156_AddMustChangePassword', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260128141915_AddRoomSeedData', '9.0.9');

ALTER TABLE "Policies" DROP COLUMN "AutoShutdownEnabled";

ALTER TABLE "Policies" DROP COLUMN "BlockUnauthorizedApplications";

ALTER TABLE "Policies" DROP COLUMN "EnableAccessControl";

ALTER TABLE "Policies" DROP COLUMN "MonitorApplicationUsage";

ALTER TABLE "Policies" DROP COLUMN "MonitorWebsiteUsage";

ALTER TABLE "Policies" DROP COLUMN "ScheduledShutdownTime";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260129145638_RemovePolicyAttributes', '9.0.9');

ALTER TABLE "Policies" ADD "WallpaperPath" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260201064848_SyncWithLatestChanges', '9.0.9');

DROP INDEX "IX_WebsiteUsageHistory_PCId_VisitedAt";

ALTER TABLE "WebsiteUsageHistory" DROP COLUMN "Url";

UPDATE "WebsiteUsageHistory" SET "Domain" = '' WHERE "Domain" IS NULL;
ALTER TABLE "WebsiteUsageHistory" ALTER COLUMN "Domain" SET NOT NULL;
ALTER TABLE "WebsiteUsageHistory" ALTER COLUMN "Domain" SET DEFAULT '';

ALTER TABLE "WebsiteUsageHistory" ADD "Browser" character varying(20) NOT NULL DEFAULT '';

CREATE UNIQUE INDEX "IX_WebsiteUsageHistory_PCId_Browser_Domain_VisitedAt" ON "WebsiteUsageHistory" ("PCId", "Browser", "Domain", "VisitedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260221131716_UpdateWebsiteUsageHistory', '9.0.9');

ALTER TABLE "Policies" ADD "CpuTemperatureCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "CpuTemperatureWarningThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "CpuUsageCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "CpuUsageWarningThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "DiskUsageCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "DiskUsageWarningThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "GpuTemperatureCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "GpuTemperatureWarningThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "LatencyCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "LatencyWarningThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "PacketLossCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "PacketLossWarningThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "RamUsageCriticalThreshold" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "Policies" ADD "RamUsageWarningThreshold" double precision NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226142212_AddPolicyThresholdProfiles', '9.0.9');

ALTER TABLE "HardwareMetrics" ADD "CpuTemperatureSource" text;

ALTER TABLE "HardwareMetrics" ADD "GpuTemperatureSource" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226143419_AddHardwareMetricSensorSources', '9.0.9');

ALTER TABLE "Policies" ADD "CriticalSustainSeconds" integer NOT NULL DEFAULT 20;

ALTER TABLE "Policies" ADD "WarningSustainSeconds" integer NOT NULL DEFAULT 30;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226144843_AddPolicySustainDurations', '9.0.9');

ALTER TABLE "HardwareMetrics" DROP COLUMN "CpuTemperatureSource";

ALTER TABLE "HardwareMetrics" DROP COLUMN "GpuTemperatureSource";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226150543_RemoveHardwareMetricSensorSources', '9.0.9');

DROP INDEX "IX_Alerts_PCId";

ALTER TABLE "Alerts" ADD "AlertKey" character varying(200) NOT NULL DEFAULT '';

ALTER TABLE "Alerts" ADD "IsResolved" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Alerts" ADD "ResolvedAt" timestamp with time zone;

CREATE INDEX "IX_Alerts_IsResolved_CreatedAt" ON "Alerts" ("IsResolved", "CreatedAt");

CREATE INDEX "IX_Alerts_PCId_AlertKey_IsResolved" ON "Alerts" ("PCId", "AlertKey", "IsResolved");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260302151032_AddAlertLifecycleState', '9.0.9');

CREATE TABLE "DeploymentLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PCId" integer,
    "PCName" character varying(120) NOT NULL,
    "IPAddress" character varying(50),
    "FileName" character varying(260) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Details" character varying(4000),
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DeploymentLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeploymentLogs_PCs_PCId" FOREIGN KEY ("PCId") REFERENCES "PCs" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_DeploymentLogs_PCId_Timestamp" ON "DeploymentLogs" ("PCId", "Timestamp");

CREATE INDEX "IX_DeploymentLogs_Timestamp" ON "DeploymentLogs" ("Timestamp");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260302162457_AddDeploymentLogs', '9.0.9');

CREATE TABLE "SystemSettings" (
    "Key" character varying(100) NOT NULL,
    "Value" character varying(500) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Key")
);

INSERT INTO "SystemSettings" ("Key", "UpdatedAt", "Value")
VALUES ('DataRetention.CleanupHourUtc', TIMESTAMPTZ '2025-01-01T00:00:00Z', '2');
INSERT INTO "SystemSettings" ("Key", "UpdatedAt", "Value")
VALUES ('DataRetention.HardwareMetricDays', TIMESTAMPTZ '2025-01-01T00:00:00Z', '30');
INSERT INTO "SystemSettings" ("Key", "UpdatedAt", "Value")
VALUES ('DataRetention.NetworkMetricDays', TIMESTAMPTZ '2025-01-01T00:00:00Z', '30');
INSERT INTO "SystemSettings" ("Key", "UpdatedAt", "Value")
VALUES ('DataRetention.ResolvedAlertDays', TIMESTAMPTZ '2025-01-01T00:00:00Z', '90');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260306160520_AddSystemSettings', '9.0.9');


            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Alerts'
                      AND column_name = 'Severity'
                      AND data_type IN ('text', 'character varying')
                ) THEN
                    ALTER TABLE "Alerts"
                    ALTER COLUMN "Severity" TYPE integer
                    USING (
                        CASE
                            WHEN "Severity" ~ '^[0-9]+$' THEN "Severity"::integer
                            WHEN lower("Severity") = 'low' THEN 0
                            WHEN lower("Severity") = 'medium' THEN 1
                            WHEN lower("Severity") = 'high' THEN 2
                            WHEN lower("Severity") = 'critical' THEN 3
                            ELSE 1
                        END
                    );
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'Alerts'
                      AND column_name = 'Type'
                      AND data_type IN ('text', 'character varying')
                ) THEN
                    ALTER TABLE "Alerts"
                    ALTER COLUMN "Type" TYPE integer
                    USING (
                        CASE
                            WHEN "Type" ~ '^[0-9]+$' THEN "Type"::integer
                            WHEN lower("Type") = 'hardware' THEN 0
                            WHEN lower("Type") = 'network' THEN 1
                            WHEN lower("Type") = 'software' THEN 2
                            WHEN lower("Type") = 'security' THEN 3
                            WHEN lower("Type") = 'system' THEN 4
                            WHEN lower("Type") = 'thermal' THEN 0
                            ELSE 4
                        END
                    );
                END IF;
            END $$;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260318155733_FixAlertEnumColumns', '9.0.9');

DROP TABLE "SoftwareInstalled";

DROP TABLE "SoftwareRequests";

DROP TABLE "Software";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260405132815_RemoveUnusedSoftwareTables', '9.0.9');

CREATE TABLE "PendingCommands" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MacAddress" character varying(50) NOT NULL,
    "CommandType" character varying(50) NOT NULL,
    "Payload" character varying(2000),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "ExpiresAtUtc" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_PendingCommands" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_PendingCommands_MacAddress_Status" ON "PendingCommands" ("MacAddress", "Status");

CREATE INDEX "IX_PendingCommands_Status_ExpiresAtUtc" ON "PendingCommands" ("Status", "ExpiresAtUtc");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260412160932_AddPendingCommands', '9.0.9');

COMMIT;

